In [63]:
import pandas as pd
import matplotlib.pyplot as plt

In [64]:
dataset_path = "dataset/dataset-uf250-1065.csv"
df = pd.read_csv(dataset_path)

# replace NaN values in 'option' by 'default'
df['option'] = df['option'].fillna('default')
df = df.fillna(0)
# remove the ' ms' from the 'Time' column and convert it to float
df['Time'] = df['Time'].str.replace(' ms', '').astype(float)
print(df.columns)
df

Index(['file', 'option', 'Time', 'Notifications', 'Done', 'Variable added',
       'Clause added', 'Clause deleted', 'Decision', 'Implication',
       'Unassignement', 'Propagation', 'Conflict', 'Backtracking started',
       'Watch added', 'Watch removed', 'Blocker set', 'Invariants checked',
       'Clause set simplified', 'Restart', 'Missed lower implication logged',
       'Missed lower implication removed', 'Lazy reimplication used',
       'Binary clause added', 'Purging clauses', 'Literal removed from clause',
       'Binary clause simplified'],
      dtype='object')

,file,option,Time,Notifications,Done,Variable added,Clause added,Clause deleted,Decision,Implication,...,Invariants checked,Clause set simplified,Restart,Missed lower implication logged,Missed lower implication removed,Lazy reimplication used,Binary clause added,Purging clauses,Literal removed from clause,Binary clause simplified
0,uf250-001.cnf,-wcb,85.0,1239831,1,251,4701,2261.0,4204,203758,...,12614,2.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,uf250-001.cnf,-lscb,77.0,1126823,1,251,4417,2266.0,3915,188326,...,11747,2.0,10.0,330.0,330.0,171.0,0.0,0.0,0.0,0.0
2,uf250-001.cnf,-gb,194.0,1846952,1,251,5239,2339.0,6140,357676,...,18422,2.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,uf250-004.cnf,default,188.0,3918985,1,251,10628,7115.0,12208,537258,...,36626,4.0,29.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,uf250-001.cnf,default,442.0,6651335,1,251,15278,11681.0,18290,808154,...,54872,5.0,43.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,uf250-099.cnf,-lscb,53209.0,656369166,1,251,286698,261712.0,322522,16209363,...,967568,12.0,876.0,26622.0,26537.0,14145.0,7.0,0.0,0.0,0.0
496,uf250-100.cnf,-wcb,49059.0,624284445,1,251,264198,171576.0,297719,15116683,...,893159,11.0,812.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0
497,uf250-099.cnf,-rscb,55874.0,739483834,1,251,311330,261672.0,349140,17545602,...,1047422,12.0,947.0,0.0,0.0,0.0,29.0,0.0,0.0,0.0
498,uf250-099.cnf,-wcb,64573.0,905709350,1,251,338377,261726.0,379595,19143715,...,1138787,12.0,1029.0,0.0,0.0,0.0,17.0,0.0,0.0,0.0
499,uf250-100.cnf,-lscb,85343.0,1242911179,1,251,393861,261720.0,444077,22690891,...,1332233,12.0,1229.0,38677.0,38531.0,20863.0,0.0,0.0,0.0,0.0

In [65]:
df_default = df[df['option'] == 'default']
df_gb = df[df['option'] == '-gb']
df_lscb = df[df['option'] == '-lscb']
df_wcb = df[df['option'] == '-wcb']
df_rscb = df[df['option'] == '-rscb']

df_options = {
    'default': df_default,
    '-wcb': df_wcb,
    '-rscb': df_rscb,
    '-lscb': df_lscb,
    '-gb': df_gb,
}

In [66]:
is_unsat = 'uuf' in dataset_path
n_vars = dataset_path.split('uf')[-1].split('-')[0]
if is_unsat:
    print("UNSAT", end=' ')
else:
    print("SAT", end=' ')
print(f"dataset with {int(len(df) / len(df_options))} problems with {n_vars} variables.")
stats = pd.DataFrame(columns=['option', 'mean_time', 'median_time', 'mean_propagations', 'median_propagations', 'mean_decisions', 'median_decisions'])
for opt, df in df_options.items():
    mean_time = f"{df['Time'].mean() / 1000:.2f} s"
    median_time = f"{df['Time'].median() / 1000:.2f} s"
    mean_propagations = f"{df['Propagation'].mean() / 10**6:.2f}  x10^6"
    median_propagations = f"{df['Propagation'].median() / 10**6:.2f}  x10^6"
    mean_decisions = f"{df['Decision'].mean() / 10**3:.2f}  x10^3"
    median_decisions = f"{df['Decision'].median() / 10**3:.2f}  x10^3"

    stats.loc[-1] = {
        'option': opt,
        'mean_time': mean_time,
        'median_time': median_time,
        'mean_propagations': mean_propagations,
        'median_propagations': median_propagations,
        'mean_decisions': mean_decisions,
        'median_decisions': median_decisions
    }
    stats.index = stats.index + 1
stats

SAT dataset with 100 problems with 250 variables.

,option,mean_time,median_time,mean_propagations,median_propagations,mean_decisions,median_decisions
4,default,31.18 s,11.07 s,5.81 x10^6,4.67 x10^6,169.05 x10^3,135.81 x10^3
3,-wcb,22.95 s,6.52 s,4.77 x10^6,3.29 x10^6,128.96 x10^3,88.41 x10^3
2,-rscb,27.20 s,8.61 s,5.73 x10^6,4.93 x10^6,145.81 x10^3,122.64 x10^3
1,-lscb,31.13 s,9.16 s,5.60 x10^6,4.17 x10^6,151.37 x10^3,112.14 x10^3
0,-gb,14.78 s,3.87 s,3.66 x10^6,2.42 x10^6,80.73 x10^3,53.16 x10^3